# Build
FROM  --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
ARG TARGETARCH

# Copy csproj and Restore as Distinct Layers
COPY *.csproj .
RUN dotnet restore -a $TARGETARCH

# Copy and Publish App & Libraries
COPY . .
RUN dotnet publish -c Release -o build

# Run
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .

# ENV
ENV ASPNETCORE_URLS=http://*:80

ENTRYPOINT ["dotnet", "Movie_Hive.dll"]