name: CI Pipeline for ASP.NET API Application using Dockerhub

on:
  push:
    branches: ['backend-api']
    tags:
      - 'v*.*.*'
  pull_request:
    branches: ['backend-api']

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          tag=${tag%% *}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Setup Git Config
        run: |
          git config user.name "Steven Chen"
          git config user.email "kwykyaw.99@gmail.com"

      - name: Save Version
        id: version
        run: echo ::set-output name=tag

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKERHUB_USERNAME }}
          password: ${{  secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Build & Push to Docker Hub Repository
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile.prod
          tags: |
            ${{  secrets.DOCKERHUB_USERNAME }}/movie_hive:${{ steps.vars.outputs.tag }}
            ${{  secrets.DOCKERHUB_USERNAME }}/movie_hive:latest
