name: CI Pipeline for ASP.NET API Application using Dockerhub

on:
  push:
    branches: ['backend-api']
    tags:
      - 'v*.*.*'
  pull_request:
    branches: ['backend-api']

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag Output
        run: |
          tag=${GITHUB_REF#refs/*/}
          tag=${tag%% *}
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movie_hive:latest,${{ secrets.DOCKERHUB_USERNAME }}/movie_hive:${{ env.tag }}
